@startuml
interface Army
interface Character
interface Unit

Army <|-- AbstractArmy
Army <|-- ArmyWithUnits
Army --> "0..*" Character : VIPs
Army --> "0..1" Character : leader
ArmyWithUnits --> Unit : has
@enduml