@startuml
hide members

interface Unit

ArmyWithUnits --> Unit : has

Unit <|-down- AbstractUnit
Unit <|-down- InfantryUnit

InfantryUnit --> Race : has
InfantryUnit --> Weapon : has
InfantryUnit --> Armor : has
@enduml